// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"yug_server/internal/data/user"
	"yug_server/internal/handlers"
	"yug_server/internal/services"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeChatHandler(db *gorm.DB, logger *zap.Logger) *handlers.ChatHandler {
	wsService := services.NewWsService(db, logger)
	chatHandler := handlers.NewChatHandler(wsService, logger)
	return chatHandler
}

func InitializeUserHandler(db *gorm.DB, logger *zap.Logger) *handlers.UserHandler {
	userRepo := user.NewUserRepo(db, logger)
	userUseCase := services.NewUserUseCase(userRepo, logger)
	userHandler := handlers.NewUserHandler(userUseCase, logger)
	return userHandler
}
